-- CreateTable
CREATE TABLE "User" (
    "email" STRING NOT NULL,
    "password" STRING NOT NULL,
    "icsUrl" STRING NOT NULL,
    "preferences" STRING NOT NULL,
    "friends" STRING[]
);

-- CreateTable
CREATE TABLE "Event" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "event_name" STRING NOT NULL,
    "start_time" TIMESTAMP(3) NOT NULL,
    "end_time" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
